### ISSUE TITLE
LocalIdGeneratorApplication 运行后不打印日志

### ISSUE THREAD

**Issue by huotaihe** [Nepxion/Aquarius#4]
您好！非常感谢你提供的这么好用的工具。
我运行 example 后发现LocalIdGeneratorApplication 的日志在控制台不打印
 LOG.info("Timer1 - Unique id={}", localIdGenerator.nextUniqueId(2, 3));

**Comment by huotaihe** [comment]
另外还请问一下，哪里可以找到Nepxion Matrix AOP 项目。
我在你的组织里和 github 上找了一下没有找到。

**Comment by HaojunRen** [comment]
不好意思，今天才看到。我这边可以打印的，估计是日志引入的问题。
Matrix AOP在首页：https://github.com/Nepxion

**Comment by huotaihe** [comment]
谢谢您的回复，我再看一下。
